//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevisedFontRatioTableDotNet.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevisedFontRatioTableDotNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Plugin_RevisedFontRatioTable.log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LOG_FILENAME {
            get {
                return ResourceManager.GetString("LOG_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLTABLE_GET_LENGTH_SHEET_NAME_MULTI {
            get {
                return ResourceManager.GetString("MLTABLE_GET_LENGTH_SHEET_NAME_MULTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可变文言信息追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MLTABLE_GET_LENGTH_SHEET_NAME_SINGLE {
            get {
                return ResourceManager.GetString("MLTABLE_GET_LENGTH_SHEET_NAME_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontRatioRevision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OUTPUT_SCRIPT_CAST_NAME {
            get {
                return ResourceManager.GetString("OUTPUT_SCRIPT_CAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // --------------------------------------------------------------------------------------------------------------------
        ///// Module for checking text cast width generated by plugin
        ///// --------------------------------------------------------------------------------------------------------------------
        ///##CPP-HEADER
        ///#include &quot;stdio.h&quot;
        ///#include &quot;FrameworkBuildOption.h&quot;
        ///
        ///#include &quot;../../../MXEOne/Platform/OpenGL/Text/MXEOne_Platform_Render_Text_Control.h&quot;
        ///#include &quot;../../../MXEOne/Include/MXEOne_Platform_Ut [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string textcast_revision {
            get {
                return ResourceManager.GetString("textcast_revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RevisedFontRatioTableWrapper.dll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WRAPPER_DLL_FILENAME {
            get {
                return ResourceManager.GetString("WRAPPER_DLL_FILENAME", resourceCulture);
            }
        }
    }
}
